
# docker buildx build --push --platform linux/amd64 --no-cache -f Dockerfile-cuda . -t sky360/sky360lib-cuda:1.0.9 -t sky360/sky360lib-cuda:latest
# docker run -it --rm -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=$DISPLAY sky360/sky360lib-cuda:latest bash

FROM sky360/bgslibrary-cuda:latest

# Install QHY sdk
WORKDIR /opt
RUN wget https://www.qhyccd.com/file/repository/publish/SDK/230111/sdk_linux64_23.01.11.tgz
RUN tar -xf sdk_linux64_23.01.11.tgz
RUN rm sdk_linux64_23.01.11.tgz
WORKDIR /opt/sdk_linux64_23.01.11
RUN bash install.sh

# Install sky360lib
WORKDIR /opt
RUN git clone --recursive https://github.com/Sky360-Repository/sky360lib.git
WORKDIR /opt/sky360lib/build
RUN cmake .. 
RUN cmake --build . -j$(nproc)
ENV PYTHONPATH=$PYTHONPATH:/opt/sky360lib/build/lib

WORKDIR /opt/sky360lib
