# v 1.0.0 - Base install
# v 1.0.1 - Changed the base conatiner to be Sky360Lib
# v 1.0.2 - Sky360Lib includes support for WMV bgs, blob detector and qhy cameras. The sky360 bgs and blod algos have speed improvements
# v 1.0.3 - Includes Vulcanexus install for prometheus exports and eProsima / prometheus-cpp build
# v 1.0.4 - Using sky360lib 1.0.3
# v 1.0.5 - Making it multi-archtecture
# v 1.0.6 - Version bump
# v 1.0.7 - Version bump
# v 1.0.8 - Version bump

# docker buildx build --push --platform linux/amd64 --no-cache -f Dockerfile-gazebo . -t sky360/ros2-humble-gazebo:1.0.9 -t sky360/ros2-humble-gazebo:latest
# docker run -it --rm -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=$DISPLAY sky360/ros2-humble-gazebo:latest bash

##############################################
# Copied from https://github.com/athackst/dockerfiles/tree/main/ros2 but using sky360 image as base
##############################################

###########################################
#  Full+Gazebo image 
###########################################

FROM sky360/ros2-humble-full:latest

ENV DEBIAN_FRONTEND=noninteractive
# Install gazebo
RUN apt-get update && apt-get install -q -y \
  lsb-release \
  wget \
  gnupg \
  sudo \
  && wget https://packages.osrfoundation.org/gazebo.gpg -O /usr/share/keyrings/pkgs-osrf-archive-keyring.gpg \
  && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/pkgs-osrf-archive-keyring.gpg] http://packages.osrfoundation.org/gazebo/ubuntu-stable $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/gazebo-stable.list > /dev/null \
  && apt-get update && apt-get install -q -y \
    ros-humble-gazebo* \
  && rm -rf /var/lib/apt/lists/*
ENV DEBIAN_FRONTEND=
