
# docker buildx build --push --platform linux/amd64,linux/arm64 --no-cache -f Dockerfile-full . -t sky360/ros2-humble-full:1.0.19 -t sky360/ros2-humble-full:latest
# docker run -it --rm -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=$DISPLAY sky360/ros2-humble-full:latest bash

##############################################
# Copied from https://github.com/athackst/dockerfiles/tree/main/ros2 but using sky360 image as base
##############################################

###########################################
#  Full image 
###########################################

FROM sky360/ros2-humble-dev:latest

ENV DEBIAN_FRONTEND=noninteractive

# Install the full release incl. Vulcanexus
RUN apt-get update && apt-get install -y \
  ros-humble-desktop \
  vulcanexus-humble-desktop \
  && rm -rf /var/lib/apt/lists/*

ENV DEBIAN_FRONTEND=
