# v 1.0.0 - Base install
# v 1.0.1 - Changed the base conatiner to be Sky360Lib
# v 1.0.2 - Sky360Lib includes support for WMV bgs, blob detector and qhy cameras. The sky360 bgs and blod algos have speed improvements

# docker build --no-cache -f Dockerfile-cuda-gazebo . -t sky360/ros2-humble-cuda-gazebo:1.0.2
# docker run -it --runtime=nvidia --gpus all --privileged --rm -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=$DISPLAY sky360/ros2-humble-cuda-gazebo:1.0.2 bash

##############################################
# Copied from https://github.com/athackst/dockerfiles/tree/main/ros2 but using sky360 image as base
##############################################

###########################################
#  Full+Gazebo CUDA image 
###########################################

FROM sky360/ros2-humble-cuda-full:1.0.2

ENV DEBIAN_FRONTEND=noninteractive
# Install gazebo
RUN apt-get update && apt-get install -q -y \
  lsb-release \
  wget \
  gnupg \
  sudo \
  && wget https://packages.osrfoundation.org/gazebo.gpg -O /usr/share/keyrings/pkgs-osrf-archive-keyring.gpg \
  && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/pkgs-osrf-archive-keyring.gpg] http://packages.osrfoundation.org/gazebo/ubuntu-stable $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/gazebo-stable.list > /dev/null \
  && apt-get update && apt-get install -q -y \
    ros-humble-gazebo* \
  && rm -rf /var/lib/apt/lists/*
ENV DEBIAN_FRONTEND=