# docker build --no-cache -f Dockerfile-cuda . -t sky360/bgslibrary-cuda:1.0.1
# docker run -it --runtime=nvidia --gpus all --privileged --rm -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=$DISPLAY sky360/bgslibrary-cuda:1.0.1 bash

FROM sky360/opencv4-cuda:4.7.0

WORKDIR /opt

RUN git clone --recursive https://github.com/Sky360-Repository/bgslibrary.git

# Compile C++ library
WORKDIR /opt/bgslibrary/build
RUN cmake .. && make -j $(nproc)

# Build and install the python wrapper
WORKDIR /opt/bgslibrary
RUN python setup.py build
RUN python setup.py install
ENV PYTHONPATH=$PYTHONPATH:/opt/bgslibrary/build/lib.linux-x86_64-cpython-38

# Compile the C++ QT User Interface
WORKDIR /opt/bgslibrary/gui/qt/build
RUN cmake .. && make -j $(nproc)
RUN cp bgslibrary_gui ../../..

# Compile examples
WORKDIR /opt/bgslibrary/examples/build
RUN cmake .. && make -j $(nproc)