# docker build --no-cache -f Dockerfile-cuda . -t sky360/simpletracker-cuda-ros2:1.0.1
# https://medium.com/ava-information/enabling-gpus-with-nvidia-docker-container-runtime-b4619d9173f5
# https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-compose-on-ubuntu-22-04
# https://stackoverflow.com/questions/25185405/using-gpu-from-a-docker-container
# docker run -it --runtime=nvidia --gpus all --privileged --rm -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=$DISPLAY sky360/simpletracker-cuda-ros2:1.0.1 bash

# if you get an error similar to this: 
#    error: (-2:Unspecified error) Can’t initialize GTK backend in function
# 1. ensure ou have exported your display i.e. edit the ~/.bashrc file and add 'export DISPLAY=:0' (excl the ' quotes) 
# where 0 is the index of your display. Its normally 0 but for me its 1
# 2. then run xhost +
# NOTE: You will need the nvidia docker runtime installed in order to run simple tracker with cuda enabled, I have added some links above for this
#
# Run the following commands at the command prompt one by one to get the application up and running
#
# source /root/.bashrc
# ./setup.sh
#
# if you see the following error: "/usr/bin/python3.10: No module named rosidl_adapter" in red, then run the following commands: 
#
# source /root/.bashrc
# ./build.sh


FROM sky360/ros2-humble-cuda-dev:opencv4.6.0

# ** [Optional] Uncomment this section to install additional packages. **

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
   && apt-get -y install --no-install-recommends python3-numpy libboost-python-dev \
   # ROS2 build related stuff
   && pip3 install setuptools==58.2.0 \
   && export PYTHONWARNINGS=ignore:::setuptools.command.install \
   && apt-get autoremove -y \
   && apt-get clean -y
   #&& rm -rf /var/lib/apt/lists/*

ENV DEBIAN_FRONTEND=dialog

WORKDIR /opt

RUN echo "if [ -f /opt/simpletracker-ros2-ws/install/setup.bash ]; then source /opt/simpletracker-ros2-ws/install/setup.bash; fi" >> /root/.bashrc

RUN git clone --recursive https://github.com/Sky360-Repository/simpletracker-ros2-ws.git

WORKDIR /opt/simpletracker-ros2-ws

#RUN ./setup.sh
#RUN source /root/.bashrc

#RUN sed -i -- "s/#('sky360/('sky360/g" ./src/simple_tracker_launch/launch/simple_tracker_launch.py
RUN sed -i -- "s/'params.yaml'/#'params.yaml'/g" ./src/simple_tracker_launch/launch/simple_tracker_launch.py
RUN sed -i -- "s/#'params-cuda.yaml'/'params-cuda.yaml'/g" ./src/simple_tracker_launch/launch/simple_tracker_launch.py